"""UUIDv7 (RFC 9562) ids: 48-bit unix-ms timestamp, then version/variant and 74 random bits.

Ids generated by one process are strictly monotonic: within the same millisecond a 12-bit counter in ``rand_a`` increments.
"""
from __future__ import annotations

import os
import threading
import time

_lock = threading.Lock()
_last_ms = 0
_seq = 0


def uuid7(now_ms: int | None = None) -> str:
    """Return a canonical lowercase UUIDv7 string."""
    global _last_ms, _seq
    with _lock:
        ms = time.time_ns() // 1_000_000 if now_ms is None else now_ms
        if ms > _last_ms:
            _last_ms = ms
            _seq = int.from_bytes(os.urandom(2), "big") & 0x1FF  # leave headroom for the counter
        else:
            ms = _last_ms
            _seq += 1
            if _seq > 0xFFF:  # counter overflow: borrow the next millisecond
                _last_ms = ms = _last_ms + 1
                _seq = 0
        seq = _seq
    rand_b = int.from_bytes(os.urandom(8), "big") & 0x3FFFFFFFFFFFFFFF
    h = (ms & 0xFFFFFFFFFFFF) << 80 | 0x7 << 76 | seq << 64 | 0b10 << 62 | rand_b
    s = f"{h:032x}"
    return f"{s[:8]}-{s[8:12]}-{s[12:16]}-{s[16:20]}-{s[20:]}"


def uuid7_ms(u: str) -> int:
    """Extract the millisecond timestamp from a UUIDv7 string."""
    return int(u.replace("-", "")[:12], 16)


def is_uuid7(u: str) -> bool:
    h = u.replace("-", "")
    return len(h) == 32 and len(u) == 36 and h[12] == "7" and h[16] in "89ab" and all(c in "0123456789abcdef" for c in h)
